# NOTEBOOK SETTINGS
[notebook]
dir = "~/datos/zk"

template = "default.md"

[group.minutes]
paths = ["minutes"]

[tool]
shell = "/bin/bash"

[group.minutes.note]
extension = "md"
template = "minutes.md"

[alias]
ls = "zk list $@"
ed = "zk edit $@"
n = "zk new $@"
min = 'zk new --no-input --no-input "$ZK_NOTEBOOK_DIR/minutes"'
